import 'dart:convert';

import 'package:sqflite/sqflite.dart';
import 'package:uuid/uuid.dart';

import '../../core/constants.dart';
import '../models/bank.dart';
import '../models/change_log.dart';
import '../models/counter_entity.dart';
import '../models/follow_up.dart';
import '../models/labour_type_def.dart';
import '../models/material_item.dart';
import '../models/material_type_def.dart';
import '../models/note.dart';
import '../models/party.dart';
import '../models/project.dart';

const _uuid = Uuid();

/// Sentinel for "argument not supplied" so update methods can distinguish
/// "leave this column alone" from "set this column to NULL". Use
/// `identical(arg, _unset)` to test — never `==`, since `==` on Object
/// could match other instances.
const Object _unset = Object();

class EntityRepository {
  EntityRepository(this._db);
  final Database _db;

  /// Cached device_id, fetched lazily from `app_settings` and reused for every
  /// audit write. The value is generated by `BackupService.ensureDeviceId` on first run.
  String? _cachedDeviceId;
  Future<String?> _deviceId() async {
    if (_cachedDeviceId != null) return _cachedDeviceId;
    final v = await getSetting('device_id');
    _cachedDeviceId = v;
    return v;
  }

  // ---- Projects ----

  Future<Project> createProject({
    required String name,
    required ProjectModel model,
    String? clientName,
    String? siteAddress,
    double? budget,
    String? projectManager,
    String? whatsapp,
    double? serviceFeePercent,
    ServiceFeeType serviceFeeType = ServiceFeeType.percent,
    double? serviceFeeAmount,
  }) async {
    final p = Project(
      id: _uuid.v4(),
      name: name.trim(),
      model: model,
      status: ProjectStatus.active,
      createdAt: DateTime.now().toUtc(),
      clientName:
          clientName?.trim().isEmpty == true ? null : clientName?.trim(),
      siteAddress:
          siteAddress?.trim().isEmpty == true ? null : siteAddress?.trim(),
      budget: budget,
      projectManager:
          projectManager?.trim().isEmpty == true ? null : projectManager?.trim(),
      whatsapp: whatsapp?.trim().isEmpty == true ? null : whatsapp?.trim(),
      serviceFeePercent: serviceFeePercent,
      serviceFeeType: serviceFeeType,
      serviceFeeAmount: serviceFeeAmount,
    );
    await _db.insert('projects', p.toMap());
    await logChange(
        entityType: 'project',
        entityId: p.id,
        action: ChangeAction.create,
        newData: p.toMap());
    return p;
  }

  Future<void> updateProjectFields(
    String id, {
    String? name,
    String? clientName,
    String? siteAddress,
    double? budget,
    String? projectManager,
    String? whatsapp,
    double? serviceFeePercent,
    ServiceFeeType? serviceFeeType,
    double? serviceFeeAmount,
    int? completionPercent,
  }) async {
    final updates = <String, Object?>{};
    if (name != null) updates['name'] = name.trim();
    if (clientName != null) {
      updates['client_name'] = clientName.trim().isEmpty ? null : clientName.trim();
    }
    if (siteAddress != null) {
      updates['site_address'] = siteAddress.trim().isEmpty ? null : siteAddress.trim();
    }
    if (budget != null) updates['budget'] = budget;
    if (projectManager != null) {
      updates['project_manager'] =
          projectManager.trim().isEmpty ? null : projectManager.trim();
    }
    if (whatsapp != null) {
      updates['whatsapp'] = whatsapp.trim().isEmpty ? null : whatsapp.trim();
    }
    if (serviceFeePercent != null) {
      updates['service_fee_percent'] = serviceFeePercent;
    }
    if (serviceFeeType != null) {
      updates['service_fee_type'] = serviceFeeType.db;
    }
    if (serviceFeeAmount != null) {
      updates['service_fee_amount'] = serviceFeeAmount;
    }
    if (completionPercent != null) {
      // Clamp to 0..100; callers can feed a slider's raw value without
      // worrying about overflow.
      updates['completion_percent'] = completionPercent.clamp(0, 100);
    }
    if (updates.isEmpty) return;
    await _db.update('projects', updates, where: 'id = ?', whereArgs: [id]);
  }

  /// Standalone helper so callers (e.g. the snapshot screen's slider) can
  /// bump completion without touching any other field.
  Future<void> updateProjectCompletion(String id, int percent) =>
      updateProjectFields(id, completionPercent: percent);

  Future<List<Project>> projects(
      {bool activeOnly = false, bool includeArchived = false}) async {
    final clauses = <String>[];
    final args = <Object>[];
    if (activeOnly) {
      clauses.add('status = ?');
      args.add(ProjectStatus.active.db);
    }
    if (!includeArchived) {
      clauses.add('is_archived = 0');
    }
    final rows = await _db.query(
      'projects',
      where: clauses.isEmpty ? null : clauses.join(' AND '),
      whereArgs: clauses.isEmpty ? null : args,
      orderBy: 'created_at DESC',
    );
    return rows.map(Project.fromMap).toList();
  }

  Future<List<Project>> archivedProjects() async {
    final rows = await _db.query(
      'projects',
      where: 'is_archived = 1',
      orderBy: 'archived_at DESC',
    );
    return rows.map(Project.fromMap).toList();
  }

  Future<Project?> project(String id) async {
    final rows = await _db.query('projects', where: 'id = ?', whereArgs: [id]);
    return rows.isEmpty ? null : Project.fromMap(rows.first);
  }

  Future<void> updateProjectStatus(String id, ProjectStatus status) async {
    await _db.update('projects', {'status': status.db},
        where: 'id = ?', whereArgs: [id]);
  }

  Future<void> updateProjectServiceFee(String id, double? percent) async {
    await _db.update('projects', {'service_fee_percent': percent},
        where: 'id = ?', whereArgs: [id]);
  }

  /// Soft-archive: preserves data, removes from active lists. Logged.
  ///
  /// **Gate**: every supplier owed money on this project must be settled
  /// (`supplierPayables == 0`). The previous design also forced
  /// `ledgerNet == 0` (total costs = total revenue), but that requirement
  /// is wrong for fixed-price With-Material contracts — the contractor's
  /// **profit** is the gap between revenue and costs, so insisting it be
  /// zero would mean refunding the profit before close. The PoC revenue
  /// recognition + loss-provision logic in
  /// [LedgerRepository.incomeFigures] already surfaces over-budget jobs
  /// and unearned customer deposits, so the user has visibility without
  /// the archive being blocked.
  ///
  /// Throws [ReconciliationException] when supplier payables are open.
  ///
  /// Pass `force: true` to bypass — only used for migrations or
  /// data-repair flows.
  Future<void> archiveProject(String id,
      {String? note, bool force = false}) async {
    final p = await project(id);
    if (p == null) return;

    if (!force) {
      final balance = await _projectLedgerBalance(id);
      if (balance.supplierPayables.abs() >= 0.01) {
        throw ReconciliationException(
          projectId: id,
          outstandingPayables: balance.supplierPayables,
          netLedger: balance.ledgerNet,
        );
      }

      // With-Material gate: if the customer has paid less than budget, the
      // user has to either record the remaining payment or shrink the
      // budget to match what was actually received. Overpayments
      // (received > budget) are allowed through — the excess is already
      // surfaced as a "deposit owed back" liability.
      if (p.model == ProjectModel.withMaterial &&
          (p.budget ?? 0) > 0 &&
          balance.received + 0.01 < (p.budget ?? 0)) {
        throw ProjectBudgetMismatchException(
          projectId: id,
          budget: p.budget!,
          received: balance.received,
        );
      }

      // Labour-Rate gate: customer money is a deposit, NOT contractor
      // income. After the service-fee reclassification, the project
      // ledger must net to zero — surplus has to be refunded to the
      // customer, deficit collected from them. Otherwise archiving
      // leaves unresolved customer money in the books.
      //
      // This is a deliberate re-introduction of the old "ledgerNet == 0"
      // requirement, but scoped only to LR. WM doesn't need it (revenue
      // legitimately exceeds costs in a fixed-price contract — that's
      // the profit).
      if (p.model == ProjectModel.labourRate &&
          balance.ledgerNet.abs() >= 0.01) {
        throw LabourRateUnsettledException(
          projectId: id,
          // `netLedger = costs − revenue`. A negative value means revenue
          // exceeds costs (surplus to refund); positive means costs
          // exceed revenue (customer underpaid, owes us). Express as
          // `netToSettle = −netLedger` so positive = refund the customer
          // (matches the LabourRateClose sign convention).
          netToSettle: -balance.ledgerNet,
        );
      }
    }

    final now = DateTime.now().toUtc();
    final dev = await _deviceId();
    await _db.transaction((txn) async {
      await txn.update(
        'projects',
        {'is_archived': 1, 'archived_at': now.toIso8601String()},
        where: 'id = ?',
        whereArgs: [id],
      );
      await txn.insert(
          'change_log',
          ChangeLog(
            id: _uuid.v4(),
            entityType: 'project',
            entityId: id,
            action: ChangeAction.archive,
            originalData: jsonEncode(p.toMap()),
            note: note,
            deviceId: dev,
            timestamp: now,
          ).toMap());
    });
  }

  /// Computes both gates that have to be satisfied before a project can be
  /// archived:
  ///
  ///   * `supplierPayables` — outstanding credit balance of
  ///     `Supplier Payables` for this project. Must be 0 (every credited
  ///     bill paid down).
  ///   * `ledgerNet` — net of the project ledger as the user sees it on
  ///     the Project Ledger screen: cost-side debits (Material, Labour)
  ///     minus credit-side income (Project Revenue, Service Fee Income).
  ///     Must be 0 — every rupee charged to the project has to be
  ///     cancelled by an inflow before archive.
  Future<_ProjectLedgerBalance> _projectLedgerBalance(String projectId) async {
    Future<double> sum(String column, String accountId) async {
      final rows = await _db.rawQuery(
        'SELECT COALESCE(SUM($column),0) AS s FROM journal_entries '
        'WHERE account_id = ? AND project_id = ? AND is_deleted = 0',
        [accountId, projectId],
      );
      return ((rows.first['s'] as num?) ?? 0).toDouble();
    }

    final supplierPaid = await sum('debit', Accounts.supplierPayables.id);
    final supplierCredits = await sum('credit', Accounts.supplierPayables.id);
    final supplierPayables = supplierCredits - supplierPaid;

    final materialDr = await sum('debit', Accounts.materialCosts.id);
    final labourDr = await sum('debit', Accounts.labourCosts.id);
    final revenueCr = await sum('credit', Accounts.projectRevenue.id);
    final feeCr = await sum('credit', Accounts.serviceFeeIncome.id);
    // For a balanced Labour-Rate project, customer money in must equal
    // customer money out:
    //     PROJECT_REV credits == costs incurred + fee charged
    //     revenueCr == (materialDr + labourDr) + feeCr
    // Rearranged into "net" form:
    //     (materialDr + labourDr + feeCr) − revenueCr == 0
    //
    // The previous formula was `(matDr + labDr) − (revCr + feeCr)` —
    // that double-counted the fee, because `postProjectServiceFee` is a
    // reclassification (Dr PROJECT_REV / Cr SERVICE_FEE_INCOME): the fee
    // is already taken out of revenue, so adding it back to the income
    // side made balanced LR projects look 2×feeCr off.
    final ledgerNet =
        (materialDr + labourDr + feeCr) - revenueCr;

    return _ProjectLedgerBalance(
      supplierPayables: supplierPayables,
      ledgerNet: ledgerNet,
      received: revenueCr,
    );
  }

  Future<void> unarchiveProject(String id) async {
    final p = await project(id);
    if (p == null) return;
    final now = DateTime.now().toUtc();
    final dev = await _deviceId();
    await _db.transaction((txn) async {
      await txn.update(
        'projects',
        {'is_archived': 0, 'archived_at': null},
        where: 'id = ?',
        whereArgs: [id],
      );
      await txn.insert(
          'change_log',
          ChangeLog(
            id: _uuid.v4(),
            entityType: 'project',
            entityId: id,
            action: ChangeAction.unarchive,
            originalData: jsonEncode(p.toMap()),
            deviceId: dev,
            timestamp: now,
          ).toMap());
    });
  }

  // ---- Suppliers ----

  Future<Party> createSupplier({
    required String name,
    String? phone,
    SupplierCategory? category,
    String? taxStatus,
    String? bankDetails,
  }) async {
    final p = Party(
      id: _uuid.v4(),
      name: name.trim(),
      phone: phone?.trim().isEmpty == true ? null : phone?.trim(),
      createdAt: DateTime.now().toUtc(),
      category: category,
      taxStatus: taxStatus?.trim().isEmpty == true ? null : taxStatus?.trim(),
      bankDetails:
          bankDetails?.trim().isEmpty == true ? null : bankDetails?.trim(),
    );
    await _db.insert('suppliers', p.toSupplierMap());
    await logChange(
        entityType: 'supplier',
        entityId: p.id,
        action: ChangeAction.create,
        newData: p.toSupplierMap());
    return p;
  }

  Future<List<Party>> suppliers({bool includeArchived = false}) async {
    final rows = await _db.query(
      'suppliers',
      where: includeArchived ? null : 'is_archived = 0',
      orderBy: 'name COLLATE NOCASE',
    );
    return rows.map(Party.fromMap).toList();
  }

  Future<List<Party>> archivedSuppliers() async {
    final rows = await _db.query(
      'suppliers',
      where: 'is_archived = 1',
      orderBy: 'archived_at DESC',
    );
    return rows.map(Party.fromMap).toList();
  }

  Future<Party?> supplier(String id) async {
    final rows =
        await _db.query('suppliers', where: 'id = ?', whereArgs: [id]);
    return rows.isEmpty ? null : Party.fromMap(rows.first);
  }

  Future<void> updateSupplierFields(
    String id, {
    String? name,
    String? phone,
    SupplierCategory? category,
    String? taxStatus,
    String? bankDetails,
  }) async {
    final updates = <String, Object?>{};
    if (name != null) updates['name'] = name.trim();
    if (phone != null) {
      updates['phone'] = phone.trim().isEmpty ? null : phone.trim();
    }
    if (category != null) updates['category'] = category.db;
    if (taxStatus != null) {
      updates['tax_status'] =
          taxStatus.trim().isEmpty ? null : taxStatus.trim();
    }
    if (bankDetails != null) {
      updates['bank_details'] =
          bankDetails.trim().isEmpty ? null : bankDetails.trim();
    }
    if (updates.isEmpty) return;

    final before = await supplier(id);
    if (before == null) return;
    final dev = await _deviceId();
    final now = DateTime.now().toUtc();
    await _db.transaction((txn) async {
      await txn.update('suppliers', updates,
          where: 'id = ?', whereArgs: [id]);
      await txn.insert(
          'change_log',
          ChangeLog(
            id: _uuid.v4(),
            entityType: 'supplier',
            entityId: id,
            action: ChangeAction.edit,
            originalData: jsonEncode(before.toSupplierMap()),
            newData: jsonEncode(updates),
            deviceId: dev,
            timestamp: now,
          ).toMap());
    });
  }

  /// Archives a supplier (material or labour). Gated on a zero payable
  /// balance so the user can't lose track of money still owed in either
  /// direction. Throws [SupplierNotSettledException] when the balance is
  /// non-zero. Pass `force: true` to bypass (migrations / data repair).
  Future<void> archiveSupplier(String id,
      {String? note, bool force = false}) async {
    final p = await supplier(id);
    if (p == null) return;

    if (!force) {
      final balance = await _supplierPayableBalance(id);
      if (balance.abs() >= 0.01) {
        throw SupplierNotSettledException(
          supplierId: id,
          outstandingBalance: balance,
        );
      }
    }

    final now = DateTime.now().toUtc();
    final dev = await _deviceId();
    await _db.transaction((txn) async {
      await txn.update(
        'suppliers',
        {'is_archived': 1, 'archived_at': now.toIso8601String()},
        where: 'id = ?',
        whereArgs: [id],
      );
      await txn.insert(
          'change_log',
          ChangeLog(
            id: _uuid.v4(),
            entityType: 'supplier',
            entityId: id,
            action: ChangeAction.archive,
            originalData: jsonEncode(p.toSupplierMap()),
            note: note,
            deviceId: dev,
            timestamp: now,
          ).toMap());
    });
  }

  /// Net Supplier Payables for one supplier, in the credit-natural
  /// direction (positive = we owe them, negative = they owe us).
  Future<double> _supplierPayableBalance(String supplierId) async {
    final rows = await _db.rawQuery(
      'SELECT COALESCE(SUM(credit),0) - COALESCE(SUM(debit),0) AS bal '
      'FROM journal_entries '
      'WHERE account_id = ? AND supplier_id = ? AND is_deleted = 0',
      [Accounts.supplierPayables.id, supplierId],
    );
    return ((rows.first['bal'] as num?) ?? 0).toDouble();
  }

  Future<void> unarchiveSupplier(String id) async {
    final p = await supplier(id);
    if (p == null) return;
    final now = DateTime.now().toUtc();
    final dev = await _deviceId();
    await _db.transaction((txn) async {
      await txn.update(
        'suppliers',
        {'is_archived': 0, 'archived_at': null},
        where: 'id = ?',
        whereArgs: [id],
      );
      await txn.insert(
          'change_log',
          ChangeLog(
            id: _uuid.v4(),
            entityType: 'supplier',
            entityId: id,
            action: ChangeAction.unarchive,
            originalData: jsonEncode(p.toSupplierMap()),
            deviceId: dev,
            timestamp: now,
          ).toMap());
    });
  }

  // ---- Banks ----

  Future<Bank> createBank({required String name, String? accountNo}) async {
    final b = Bank(
      id: _uuid.v4(),
      name: name.trim(),
      accountNo: accountNo?.trim().isEmpty == true ? null : accountNo?.trim(),
      createdAt: DateTime.now().toUtc(),
    );
    await _db.insert('banks', b.toMap());
    await logChange(
        entityType: 'bank',
        entityId: b.id,
        action: ChangeAction.create,
        newData: b.toMap());
    return b;
  }

  Future<List<Bank>> banks({bool includeArchived = false}) async {
    final rows = await _db.query(
      'banks',
      where: includeArchived ? null : 'is_archived = 0',
      orderBy: 'name COLLATE NOCASE',
    );
    return rows.map(Bank.fromMap).toList();
  }

  Future<List<Bank>> archivedBanks() async {
    final rows = await _db.query(
      'banks',
      where: 'is_archived = 1',
      orderBy: 'archived_at DESC',
    );
    return rows.map(Bank.fromMap).toList();
  }

  Future<Bank?> bank(String id) async {
    final rows = await _db.query('banks', where: 'id = ?', whereArgs: [id]);
    return rows.isEmpty ? null : Bank.fromMap(rows.first);
  }

  Future<void> updateBankFields(
    String id, {
    String? name,
    String? accountNo,
  }) async {
    final updates = <String, Object?>{};
    if (name != null) updates['name'] = name.trim();
    if (accountNo != null) {
      updates['account_no'] =
          accountNo.trim().isEmpty ? null : accountNo.trim();
    }
    if (updates.isEmpty) return;
    final before = await bank(id);
    if (before == null) return;
    final dev = await _deviceId();
    final now = DateTime.now().toUtc();
    await _db.transaction((txn) async {
      await txn.update('banks', updates, where: 'id = ?', whereArgs: [id]);
      await txn.insert(
          'change_log',
          ChangeLog(
            id: _uuid.v4(),
            entityType: 'bank',
            entityId: id,
            action: ChangeAction.edit,
            originalData: jsonEncode(before.toMap()),
            newData: jsonEncode(updates),
            deviceId: dev,
            timestamp: now,
          ).toMap());
    });
  }

  Future<void> archiveBank(String id, {String? note}) async {
    final b = await bank(id);
    if (b == null) return;
    final now = DateTime.now().toUtc();
    final dev = await _deviceId();
    await _db.transaction((txn) async {
      await txn.update(
        'banks',
        {'is_archived': 1, 'archived_at': now.toIso8601String()},
        where: 'id = ?',
        whereArgs: [id],
      );
      await txn.insert(
          'change_log',
          ChangeLog(
            id: _uuid.v4(),
            entityType: 'bank',
            entityId: id,
            action: ChangeAction.archive,
            originalData: jsonEncode(b.toMap()),
            note: note,
            deviceId: dev,
            timestamp: now,
          ).toMap());
    });
  }

  Future<void> unarchiveBank(String id) async {
    final b = await bank(id);
    if (b == null) return;
    final now = DateTime.now().toUtc();
    final dev = await _deviceId();
    await _db.transaction((txn) async {
      await txn.update(
        'banks',
        {'is_archived': 0, 'archived_at': null},
        where: 'id = ?',
        whereArgs: [id],
      );
      await txn.insert(
          'change_log',
          ChangeLog(
            id: _uuid.v4(),
            entityType: 'bank',
            entityId: id,
            action: ChangeAction.unarchive,
            originalData: jsonEncode(b.toMap()),
            deviceId: dev,
            timestamp: now,
          ).toMap());
    });
  }

  /// Delete a bank IFF it has never been used in a journal entry. Otherwise
  /// throws — historical balances must keep referring to a real account.
  /// Most callers should use [archiveBank] instead so the audit trail stays
  /// intact.
  Future<void> deleteBank(String id) async {
    final used = await _db.rawQuery(
      'SELECT 1 FROM journal_entries WHERE account_id = ? LIMIT 1',
      [id],
    );
    if (used.isNotEmpty) {
      throw StateError(
          'Bank/wallet $id is referenced by journal entries and cannot be deleted. Archive it instead.');
    }
    await _db.delete('banks', where: 'id = ?', whereArgs: [id]);
  }

  // ---- Counter Entities ----

  Future<CounterEntity> createCounterEntity({
    required String name,
    required CounterEntityType type,
    double amount = 0,
  }) async {
    final e = CounterEntity(
      id: _uuid.v4(),
      name: name.trim(),
      type: type,
      amount: amount,
      createdAt: DateTime.now().toUtc(),
    );
    await _db.insert('counter_entities', e.toMap());
    return e;
  }

  Future<List<CounterEntity>> counterEntities() async {
    final rows =
        await _db.query('counter_entities', orderBy: 'name COLLATE NOCASE');
    return rows.map(CounterEntity.fromMap).toList();
  }

  Future<void> updateCounterEntityAmount(String id, double amount) async {
    await _db.update('counter_entities', {'amount': amount},
        where: 'id = ?', whereArgs: [id]);
  }

  // ---- Material Inventory ----

  /// Records a material purchase against [material_inventory].
  ///
  /// Quantity is optional. When a positive [quantity] is supplied we store it
  /// with the derived per-unit `rate` (`price / quantity`) so the Material
  /// Price Trend can plot this purchase. When it is omitted we still log the
  /// row — so the per-type cost breakdown keeps the material-type attribution
  /// — but with a null quantity and null rate, which the price-trend query
  /// skips. The cost detail then lives in the transaction memo.
  ///
  /// `supplierId` is nullable: counter-purchase rows aren't tied to a
  /// supplier. Schema v12 made the column nullable to support this.
  Future<MaterialItem> logMaterialPurchase({
    required String projectId,
    String? supplierId,
    String? transactionId,
    required String materialType,
    required double price,
    double? quantity,
    MaterialUnit? unit,
  }) async {
    final bool hasQty = quantity != null && quantity > 0;
    final item = MaterialItem(
      id: _uuid.v4(),
      projectId: projectId,
      supplierId: supplierId,
      transactionId: transactionId,
      materialType: materialType,
      unit: unit ?? MaterialUnit.lump,
      quantity: hasQty ? quantity : null,
      rate: hasQty ? price / quantity : null,
      totalCost: price,
      txnType: MaterialTxnType.purchase,
      createdAt: DateTime.now().toUtc(),
    );
    await _db.insert('material_inventory', item.toMap());
    return item;
  }

  // ---- Material Types (user-defined categories) ----

  /// All material categories, built-ins first then alphabetical for the rest.
  /// `sort_order` lets the seeded built-ins (Brick, Cement, Sarya, Finishing,
  /// Other) keep their original order; user rows fall back to insertion time.
  Future<List<MaterialTypeDef>> materialTypes() async {
    final rows = await _db.query(
      'material_types',
      orderBy: 'is_builtin DESC, sort_order ASC, name ASC',
    );
    return rows.map(MaterialTypeDef.fromMap).toList();
  }

  /// Adds a new user-defined material type. Trims whitespace and rejects
  /// duplicates (case-insensitive) to keep the dropdown clean. Returns the
  /// row, or `null` if [name] was empty.
  ///
  /// All procurement metadata is optional — the caller can record only the
  /// name and edit the rest later from the type's detail screen.
  ///
  /// Throws if a row with the same name already exists.
  Future<MaterialTypeDef?> addMaterialType(
    String name, {
    UomType? uomType,
    String? uom,
    double? coverageRate,
    MaterialDims? dims,
  }) async {
    final clean = name.trim();
    if (clean.isEmpty) return null;

    final existing = await _db.query(
      'material_types',
      where: 'LOWER(name) = LOWER(?)',
      whereArgs: [clean],
      limit: 1,
    );
    if (existing.isNotEmpty) {
      throw StateError('A material type named "$clean" already exists.');
    }

    final row = MaterialTypeDef(
      id: _uuid.v4(),
      name: clean,
      isBuiltin: false,
      // Pushes user-added rows after the built-ins and any earlier customs.
      sortOrder: 1000 + DateTime.now().millisecondsSinceEpoch ~/ 1000,
      uomType: uomType,
      uom: uom,
      coverageRate: coverageRate,
      dims: dims,
      createdAt: DateTime.now().toUtc(),
    );
    await _db.insert('material_types', row.toMap());
    return row;
  }

  /// Updates editable fields on an existing material type. Built-ins can be
  /// renamed and have their procurement metadata edited, but they cannot be
  /// deleted (so historical inventory rows always resolve to a label).
  ///
  /// Pass `null` for any field to clear it (e.g. removing a coverage rate).
  /// Pass nothing (omit the named arg) to leave it unchanged.
  Future<void> updateMaterialType(
    String id, {
    Object? name = _unset,
    Object? uomType = _unset,
    Object? uom = _unset,
    Object? coverageRate = _unset,
    Object? dims = _unset,
  }) async {
    final patch = <String, Object?>{};
    if (!identical(name, _unset)) {
      final cleaned = (name as String?)?.trim();
      if (cleaned == null || cleaned.isEmpty) return;
      patch['name'] = cleaned;
    }
    if (!identical(uomType, _unset)) {
      patch['uom_typ'] = (uomType as UomType?)?.db;
    }
    if (!identical(uom, _unset)) {
      final cleaned = (uom as String?)?.trim();
      patch['uom'] = (cleaned == null || cleaned.isEmpty) ? null : cleaned;
    }
    if (!identical(coverageRate, _unset)) {
      patch['cov_rate'] = coverageRate as double?;
    }
    if (!identical(dims, _unset)) {
      final d = dims as MaterialDims?;
      patch['dims'] = (d == null || d.isEmpty) ? null : jsonEncode(d.toJson());
    }
    if (patch.isEmpty) return;
    await _db
        .update('material_types', patch, where: 'id = ?', whereArgs: [id]);
  }

  /// Backwards-compatible helper for callers that only need to rename.
  Future<void> renameMaterialType(String id, String newName) =>
      updateMaterialType(id, name: newName);

  /// Deletes a material type. Every row is freely deletable now —
  /// historical material_inventory rows store the type name as a free-form
  /// string, so removing the catalog row only hides the option from the
  /// Buy Material dropdown going forward.
  Future<bool> deleteMaterialType(String id) async {
    final n = await _db.delete(
      'material_types',
      where: 'id = ?',
      whereArgs: [id],
    );
    return n > 0;
  }

  Future<List<MaterialItem>> materialInventory({String? projectId}) async {
    // Excludes rows whose parent journal txn has been soft- or hard-
    // deleted (v13 linkage). Add an `includeDeleted` flag here if a
    // future audit screen needs to show them.
    final whereClauses = <String>['is_deleted = 0'];
    final args = <Object>[];
    if (projectId != null) {
      whereClauses.add('project_id = ?');
      args.add(projectId);
    }
    final rows = await _db.query(
      'material_inventory',
      where: whereClauses.join(' AND '),
      whereArgs: args,
      orderBy: 'created_at DESC',
    );
    return rows.map(MaterialItem.fromMap).toList();
  }

  // ---- Labour Types ----

  Future<List<LabourTypeDef>> labourTypes() async {
    final rows = await _db.query('labour_types', orderBy: 'name ASC');
    return rows.map(LabourTypeDef.fromMap).toList();
  }

  Future<LabourTypeDef?> addLabourType(
    String name, {
    String? description,
    double? defaultDailyRate,
  }) async {
    final clean = name.trim();
    if (clean.isEmpty) return null;
    final existing = await _db.query(
      'labour_types',
      where: 'LOWER(name) = LOWER(?)',
      whereArgs: [clean],
      limit: 1,
    );
    if (existing.isNotEmpty) {
      throw StateError('A labour type named "$clean" already exists.');
    }
    final row = LabourTypeDef(
      id: _uuid.v4(),
      name: clean,
      description: description?.trim().isEmpty == true ? null : description?.trim(),
      defaultDailyRate: defaultDailyRate,
      createdAt: DateTime.now().toUtc(),
    );
    await _db.insert('labour_types', row.toMap());
    return row;
  }

  Future<void> updateLabourType(
    String id, {
    Object? name = _unset,
    Object? description = _unset,
    Object? defaultDailyRate = _unset,
  }) async {
    final patch = <String, Object?>{};
    if (!identical(name, _unset)) {
      final cleaned = (name as String?)?.trim();
      if (cleaned == null || cleaned.isEmpty) return;
      patch['name'] = cleaned;
    }
    if (!identical(description, _unset)) {
      final cleaned = (description as String?)?.trim();
      patch['description'] = (cleaned == null || cleaned.isEmpty) ? null : cleaned;
    }
    if (!identical(defaultDailyRate, _unset)) {
      patch['default_daily_rate'] = defaultDailyRate as double?;
    }
    if (patch.isEmpty) return;
    await _db.update('labour_types', patch, where: 'id = ?', whereArgs: [id]);
  }

  Future<bool> deleteLabourType(String id) async {
    final n = await _db.delete('labour_types', where: 'id = ?', whereArgs: [id]);
    return n > 0;
  }

  // ---- Notes (v14: operational memory) ----

  /// Notes for one entity (project / supplier), pinned first then
  /// newest-first. Soft-deleted rows are excluded.
  Future<List<Note>> notesFor(NoteEntityType type, String entityId) async {
    final rows = await _db.query(
      'notes',
      where: 'entity_type = ? AND entity_id = ? AND is_deleted = 0',
      whereArgs: [type.db, entityId],
      orderBy: 'is_pinned DESC, created_at DESC',
    );
    return rows.map(Note.fromMap).toList();
  }

  /// Cross-entity search for the global note browser. Case-insensitive
  /// substring match on the note body; results are ordered pinned-first
  /// then newest-first.
  Future<List<Note>> searchNotes(String query) async {
    final q = query.trim();
    if (q.isEmpty) return const [];
    final rows = await _db.query(
      'notes',
      where: 'is_deleted = 0 AND body LIKE ? COLLATE NOCASE',
      whereArgs: ['%$q%'],
      orderBy: 'is_pinned DESC, created_at DESC',
      limit: 200,
    );
    return rows.map(Note.fromMap).toList();
  }

  Future<Note> addNote({
    required NoteEntityType type,
    required String entityId,
    required String body,
    bool pinned = false,
  }) async {
    final clean = body.trim();
    if (clean.isEmpty) {
      throw ArgumentError('Note body must not be empty.');
    }
    final n = Note(
      id: _uuid.v4(),
      entityType: type,
      entityId: entityId,
      body: clean,
      isPinned: pinned,
      createdAt: DateTime.now().toUtc(),
    );
    await _db.insert('notes', n.toMap());
    return n;
  }

  Future<void> updateNoteBody(String id, String body) async {
    final clean = body.trim();
    if (clean.isEmpty) return;
    await _db.update(
      'notes',
      {
        'body': clean,
        'updated_at': DateTime.now().toUtc().toIso8601String(),
      },
      where: 'id = ?',
      whereArgs: [id],
    );
  }

  Future<void> toggleNotePin(String id, bool pinned) async {
    await _db.update(
      'notes',
      {'is_pinned': pinned ? 1 : 0},
      where: 'id = ?',
      whereArgs: [id],
    );
  }

  /// Soft-delete. Hard-delete is never exposed — keeping the row lets a
  /// future "trash" surface restore it.
  Future<void> deleteNote(String id) async {
    await _db.update(
      'notes',
      {
        'is_deleted': 1,
        'deleted_at': DateTime.now().toUtc().toIso8601String(),
      },
      where: 'id = ?',
      whereArgs: [id],
    );
  }

  // ---- Follow-Ups (v14: customer recovery / promise tracking) ----

  /// All pending follow-ups, sorted overdue-first then by priority
  /// (high → low) then by expected date (soonest first).
  Future<List<FollowUp>> pendingFollowUps() async {
    final rows = await _db.query(
      'follow_ups',
      where: "status = 'pending' AND is_deleted = 0",
      orderBy: 'created_at DESC',
    );
    final list = rows.map(FollowUp.fromMap).toList();
    final now = DateTime.now();
    int priorityRank(FollowUpPriority p) => switch (p) {
          FollowUpPriority.high => 0,
          FollowUpPriority.medium => 1,
          FollowUpPriority.low => 2,
        };
    list.sort((a, b) {
      final aOverdue = a.isOverdue(now);
      final bOverdue = b.isOverdue(now);
      if (aOverdue != bOverdue) return aOverdue ? -1 : 1;
      final pr = priorityRank(a.priority).compareTo(priorityRank(b.priority));
      if (pr != 0) return pr;
      final ad = a.expectedDate ?? DateTime(9999);
      final bd = b.expectedDate ?? DateTime(9999);
      return ad.compareTo(bd);
    });
    return list;
  }

  /// Overdue follow-ups only (pending + expected_date < now). Used by the
  /// dashboard tile so the user is nudged to chase late commitments.
  Future<List<FollowUp>> overdueFollowUps() async {
    final pending = await pendingFollowUps();
    final now = DateTime.now();
    return pending.where((f) => f.isOverdue(now)).toList();
  }

  /// Resolved (or cancelled) follow-ups for the history surface.
  Future<List<FollowUp>> archivedFollowUps() async {
    final rows = await _db.query(
      'follow_ups',
      where: "status IN ('resolved', 'cancelled') AND is_deleted = 0",
      orderBy: 'resolved_at DESC, created_at DESC',
    );
    return rows.map(FollowUp.fromMap).toList();
  }

  Future<List<FollowUp>> followUpsForProject(String projectId) async {
    final rows = await _db.query(
      'follow_ups',
      where: 'project_id = ? AND is_deleted = 0',
      whereArgs: [projectId],
      orderBy: "status = 'pending' DESC, created_at DESC",
    );
    return rows.map(FollowUp.fromMap).toList();
  }

  Future<FollowUp> addFollowUp({
    required String title,
    String? note,
    String? projectId,
    String? supplierId,
    DateTime? expectedDate,
    FollowUpPriority priority = FollowUpPriority.medium,
    double? amountEstimate,
  }) async {
    final clean = title.trim();
    if (clean.isEmpty) {
      throw ArgumentError('Follow-up title must not be empty.');
    }
    final f = FollowUp(
      id: _uuid.v4(),
      projectId: projectId,
      supplierId: supplierId,
      title: clean,
      note: note?.trim().isEmpty == true ? null : note?.trim(),
      expectedDate: expectedDate?.toUtc(),
      priority: priority,
      status: FollowUpStatus.pending,
      amountEstimate: amountEstimate,
      createdAt: DateTime.now().toUtc(),
    );
    await _db.insert('follow_ups', f.toMap());
    return f;
  }

  Future<void> updateFollowUp(
    String id, {
    String? title,
    String? note,
    DateTime? expectedDate,
    FollowUpPriority? priority,
    double? amountEstimate,
  }) async {
    final updates = <String, Object?>{};
    if (title != null) {
      final clean = title.trim();
      if (clean.isEmpty) return;
      updates['title'] = clean;
    }
    if (note != null) {
      updates['note'] = note.trim().isEmpty ? null : note.trim();
    }
    if (expectedDate != null) {
      updates['expected_date'] = expectedDate.toUtc().toIso8601String();
    }
    if (priority != null) updates['priority'] = priority.db;
    if (amountEstimate != null) updates['amount_estimate'] = amountEstimate;
    if (updates.isEmpty) return;
    await _db.update('follow_ups', updates, where: 'id = ?', whereArgs: [id]);
  }

  Future<void> resolveFollowUp(String id) async {
    await _db.update(
      'follow_ups',
      {
        'status': FollowUpStatus.resolved.db,
        'resolved_at': DateTime.now().toUtc().toIso8601String(),
      },
      where: 'id = ?',
      whereArgs: [id],
    );
  }

  Future<void> cancelFollowUp(String id) async {
    await _db.update(
      'follow_ups',
      {
        'status': FollowUpStatus.cancelled.db,
        'resolved_at': DateTime.now().toUtc().toIso8601String(),
      },
      where: 'id = ?',
      whereArgs: [id],
    );
  }

  Future<void> reopenFollowUp(String id) async {
    await _db.update(
      'follow_ups',
      {
        'status': FollowUpStatus.pending.db,
        'resolved_at': null,
      },
      where: 'id = ?',
      whereArgs: [id],
    );
  }

  Future<void> deleteFollowUp(String id) async {
    await _db.update(
      'follow_ups',
      {
        'is_deleted': 1,
        'deleted_at': DateTime.now().toUtc().toIso8601String(),
      },
      where: 'id = ?',
      whereArgs: [id],
    );
  }

  // ---- Cloud sync state (v15) ----

  /// Returns the tenant UUID for this operator's data scope on Supabase.
  ///
  /// Resolution order:
  ///   1. **Build-time fixed tenant** (`SupabaseConfig.tenantId`, from the
  ///      `SUPABASE_TENANT_ID` dart-define). When set it always wins and is
  ///      persisted, so every install of this build shares one tenant and
  ///      sync works from first launch with no manual copying. It also
  ///      overrides any stale random tenant a previous build stored.
  ///   2. Otherwise the value previously stored in `app_settings`.
  ///   3. Otherwise a fresh random UUID, generated once and persisted
  ///      (legacy per-install behaviour, used only in builds with no baked
  ///      tenant — e.g. tests).
  Future<String> ensureTenantId() async {
    final baked = SupabaseConfig.tenantId;
    if (baked.isNotEmpty) {
      final existing = await getSetting(SettingsKeys.tenantId);
      if (existing != baked) await setSetting(SettingsKeys.tenantId, baked);
      return baked;
    }
    final existing = await getSetting(SettingsKeys.tenantId);
    if (existing != null && existing.isNotEmpty) return existing;
    final fresh = _uuid.v4();
    await setSetting(SettingsKeys.tenantId, fresh);
    return fresh;
  }

  Future<String?> tenantIdOrNull() => getSetting(SettingsKeys.tenantId);

  Future<void> setTenantId(String tenantId) =>
      setSetting(SettingsKeys.tenantId, tenantId);

  /// `true` when the operator has opted into cloud sync. Defaults to
  /// `true` so the first launch on a configured build enables sync
  /// automatically (matching the original auto-start behaviour). Toggle
  /// from Settings.
  Future<bool> cloudSyncEnabled() async {
    final v = await getSetting(SettingsKeys.cloudSyncEnabled);
    if (v == null) return true;
    return v == '1' || v.toLowerCase() == 'true';
  }

  Future<void> setCloudSyncEnabled(bool enabled) =>
      setSetting(SettingsKeys.cloudSyncEnabled, enabled ? '1' : '0');

  /// Last point at which a successful push for [table] completed. The
  /// next push only sends rows whose `updated_at` is strictly greater.
  Future<DateTime?> pushCursor(String table) async {
    final v = await getSetting(SettingsKeys.pushCursor(table));
    if (v == null || v.isEmpty) return null;
    return DateTime.tryParse(v);
  }

  Future<void> setPushCursor(String table, DateTime at) =>
      setSetting(SettingsKeys.pushCursor(table), at.toUtc().toIso8601String());

  Future<DateTime?> pullCursor(String table) async {
    final v = await getSetting(SettingsKeys.pullCursor(table));
    if (v == null || v.isEmpty) return null;
    return DateTime.tryParse(v);
  }

  Future<void> setPullCursor(String table, DateTime at) =>
      setSetting(SettingsKeys.pullCursor(table), at.toUtc().toIso8601String());

  /// Clears every stored pull cursor so the next sync re-downloads all
  /// server rows for the current tenant from the beginning of time. Powers
  /// the "re-pull everything" recovery action. Pulls are INSERT OR IGNORE,
  /// so this can never overwrite a local row — it only back-fills rows this
  /// device never pulled. Safe to call any time.
  Future<void> resetPullCursors() async {
    await _db.delete('app_settings', where: "key LIKE 'cloud_pull_at:%'");
  }

  // ---- Settings ----

  Future<String?> getSetting(String key) async {
    final rows = await _db.query('app_settings',
        where: 'key = ?', whereArgs: [key], limit: 1);
    return rows.isEmpty ? null : rows.first['value'] as String?;
  }

  Future<void> setSetting(String key, String? value) async {
    await _db.insert(
      'app_settings',
      {'key': key, 'value': value},
      conflictAlgorithm: ConflictAlgorithm.replace,
    );
  }

  // ---- Change Log ----

  Future<List<ChangeLog>> changeLog({String? entityType, int? limit}) async {
    final rows = await _db.query(
      'change_log',
      where: entityType == null ? null : 'entity_type = ?',
      whereArgs: entityType == null ? null : [entityType],
      orderBy: 'timestamp DESC',
      limit: limit,
    );
    return rows.map(ChangeLog.fromMap).toList();
  }

  Future<void> logChange({
    required String entityType,
    required String entityId,
    required ChangeAction action,
    Map<String, Object?>? originalData,
    Map<String, Object?>? newData,
    String? note,
  }) async {
    await _db.insert(
        'change_log',
        ChangeLog(
          id: _uuid.v4(),
          entityType: entityType,
          entityId: entityId,
          action: action,
          originalData:
              originalData == null ? null : jsonEncode(originalData),
          newData: newData == null ? null : jsonEncode(newData),
          note: note,
          deviceId: await _deviceId(),
          timestamp: DateTime.now().toUtc(),
        ).toMap());
  }
}

/// Internal struct for [EntityRepository._projectLedgerBalance]. Exists
/// purely to bundle the two gating numbers the archive guard needs.
class _ProjectLedgerBalance {
  final double supplierPayables;
  final double ledgerNet;
  /// Total project revenue credits (sum of all "Received from project"
  /// transactions, net of any service-fee reclassification).
  final double received;
  const _ProjectLedgerBalance({
    required this.supplierPayables,
    required this.ledgerNet,
    required this.received,
  });

  /// Gate fails when either side has not been zeroed out (1 paisa
  /// tolerance to absorb floating-point noise from divisions).
  bool get isOutOfBalance =>
      supplierPayables.abs() >= 0.01 || ledgerNet.abs() >= 0.01;
}

/// Thrown when an attempt is made to archive a project whose ledger has
/// not been fully reconciled. Carries both the outstanding supplier
/// payable balance and the project ledger net so the UI can tell the
/// user what's wrong.
class ReconciliationException implements Exception {
  final String projectId;
  final double outstandingPayables;
  final double netLedger;
  const ReconciliationException({
    required this.projectId,
    required this.outstandingPayables,
    this.netLedger = 0,
  });
  @override
  String toString() => 'ReconciliationException(project=$projectId, '
      'outstandingPayables=$outstandingPayables, netLedger=$netLedger)';
}

/// Thrown when a Labour-Rate project is being archived but the project
/// ledger has not been balanced to zero — i.e. customer money is still
/// unsettled. For an LR project the contractor only earns the service
/// fee; everything else is pass-through, so any surplus must be refunded
/// and any deficit collected before close.
///
/// `netToSettle` follows the same sign convention as [LabourRateClose]:
///   * Positive → contractor is holding the customer's surplus → refund.
///   * Negative → customer underpaid → collect the deficit.
class LabourRateUnsettledException implements Exception {
  final String projectId;
  final double netToSettle;
  const LabourRateUnsettledException({
    required this.projectId,
    required this.netToSettle,
  });
  double get refundToCustomer => netToSettle > 0 ? netToSettle : 0;
  double get customerOwesUs => netToSettle < 0 ? -netToSettle : 0;
  @override
  String toString() => 'LabourRateUnsettledException(project=$projectId, '
      'netToSettle=$netToSettle)';
}

/// Thrown when a With-Material project is being archived but the customer
/// has paid less than the budget — i.e. there is still money outstanding
/// or the contract value was effectively renegotiated downward. The UI
/// catches this and offers to adjust the budget to match the received
/// amount (resizing the contract) or cancel.
///
/// `received > budget` is **not** a mismatch for this purpose: the excess
/// is already tracked as a refund-able customer deposit by the PoC logic
/// in [LedgerRepository.incomeFigures], and archiving with that liability
/// in place is the correct accounting outcome.
class ProjectBudgetMismatchException implements Exception {
  final String projectId;
  final double budget;
  final double received;
  const ProjectBudgetMismatchException({
    required this.projectId,
    required this.budget,
    required this.received,
  });
  double get shortfall => budget - received;
  @override
  String toString() => 'ProjectBudgetMismatchException(project=$projectId, '
      'budget=$budget, received=$received)';
}

/// Thrown when an attempt is made to archive a supplier whose payable
/// balance is not zero. The UI catches this and tells the user how much
/// is still owed (or owed-to-us).
class SupplierNotSettledException implements Exception {
  final String supplierId;
  final double outstandingBalance;
  const SupplierNotSettledException({
    required this.supplierId,
    required this.outstandingBalance,
  });
  @override
  String toString() => 'SupplierNotSettledException(supplier=$supplierId, '
      'balance=$outstandingBalance)';
}
